### ISSUE TITLE
jGRASP not opening

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#183]
```
$ /opt/jgrasp/bin/jgrasp
Error at jGRASP startup:
Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper

java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1494)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1312)
	at java.desktop/javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
	at Grasp.a(Grasp.java:210)
	at Grasp.main(Grasp.java:201)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 16 more
```

**Comment by kylelaker** [comment]
I updated these packages today:

```
Start-Date: 2018-08-25  10:07:59
Requested-By: lakerka (1000)
Upgrade: libavformat57:amd64 (7:3.4.2-2, 7:3.4.4-0ubuntu0.18.04.1), libpangoft2-1.0-0:amd64 (1.40.14-1, 1.40.14-1ubuntu0.1), linux-libc-dev:amd64 (4.15.0-32.35, 4.15.0-33.36), libapt-inst2.0:amd64 (1.6.3, 1.6.3ubuntu0.1), libswresample2:amd64 (7:3.4.2-2, 7:3.4.4-0ubuntu0.18.04.1), grub-common:amd64 (2.02-2ubuntu8.2, 2.02-2ubuntu8.3), apt:amd64 (1.6.3, 1.6.3ubuntu0.1), gir1.2-pango-1.0:amd64 (1.40.14-1, 1.40.14-1ubuntu0.1), grub2-common:amd64 (2.02-2ubuntu8.2, 2.02-2ubuntu8.3), libapt-pkg5.0:amd64 (1.6.3, 1.6.3ubuntu0.1), grub-pc:amd64 (2.02-2ubuntu8.2, 2.02-2ubuntu8.3), openjdk-11-jre-headless:amd64 (10.0.1+10-3ubuntu1, 10.0.2+13-1ubuntu0.18.04.1), grub-pc-bin:amd64 (2.02-2ubuntu8.2, 2.02-2ubuntu8.3), libpangoxft-1.0-0:amd64 (1.40.14-1, 1.40.14-1ubuntu0.1), libpangocairo-1.0-0:amd64 (1.40.14-1, 1.40.14-1ubuntu0.1), openjdk-11-jdk:amd64 (10.0.1+10-3ubuntu1, 10.0.2+13-1ubuntu0.18.04.1), openjdk-11-jre:amd64 (10.0.1+10-3ubuntu1, 10.0.2+13-1ubuntu0.18.04.1), libavcodec57:amd64 (7:3.4.2-2, 7:3.4.4-0ubuntu0.18.04.1), libavutil55:amd64 (7:3.4.2-2, 7:3.4.4-0ubuntu0.18.04.1), wpasupplicant:amd64 (2:2.6-15ubuntu2, 2:2.6-15ubuntu2.1), apt-utils:amd64 (1.6.3, 1.6.3ubuntu0.1), libswscale4:amd64 (7:3.4.2-2, 7:3.4.4-0ubuntu0.18.04.1), libmozjs-52-0:amd64 (52.8.1-0ubuntu0.18.04.1, 52.9.1-0ubuntu0.18.04.1), libpango-1.0-0:amd64 (1.40.14-1, 1.40.14-1ubuntu0.1), openjdk-11-jdk-headless:amd64 (10.0.1+10-3ubuntu1, 10.0.2+13-1ubuntu0.18.04.1)
End-Date: 2018-08-25  10:08:27

Start-Date: 2018-08-25  10:12:12
Requested-By: lakerka (1000)
End-Date: 2018-08-25  10:12:12
```

It is still broken with jGRASP 2.0.5_01 (released 2018-08-16).

**Comment by kylelaker** [comment]
It seems like we're going to have to use the workaroud: comment out the line in `/etc/java-11-openjdk/accessibility.properties/`. We should follow the upstream issue and ensure that we re-enable loading the assistive technologies once there is a better solution.

**Comment by ripleymj** [comment]
Thanks GitHub

**Comment by kylelaker** [comment]
@ripleymj Thoughts on just forcing our own 

```
#
# The following line specifies the assistive technology classes 
# that should be loaded into the Java VM when the AWT is initailized.
# Specify multiple classes by separating them with commas.
# Note: the line below cannot end the file (there must be at
# a minimum a blank line following it).
#
# Line commented to resolve jmunixusers/cs-vm-build#183
#assistive_technologies=org.GNOME.Accessibility.AtkWrapper
```

into  `/etc/java-11-openjdk/accessibility.properties`? It might get overwritten whenever `openjdk-11-jre-headless` updates but so would any slightly-more-polite way of commenting out that line. It also allows use to comment why it's disabled.

**Comment by ripleymj** [comment]
Just using the `file` module? I'd considered it, but assumed it would offend you. If you've arrived at the same conclusion, go for it.
