### ISSUE TITLE
Finch robots PYTHONPATH broken

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/cs-vm-build#450]
The `PYTHONPATH` and `HIDAPI_LIB_PATH` that we are setting for the Finch robots are broken. Observe the following:

```
# Check the two variable
$ echo $PYTHONPATH
:/opt/FinchPython

$ echo $HIDAPI_LIB_PATH
/opt/FinchPython

# Attempt to import the `finch` module
$ python3 -c 'import finch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'finch'

# Inspect the directory on our Python path, see that `finch.py` is not in that directory
$ ls /opt/FinchPython
dance2.py  FinchPython120  maze.py

# Fix the PYTHON path and try again
$ export PYTHONPATH=:/opt/FinchPython/FinchPython120

# See that now the HIDAPI_LIB_PATH is broken
$ python3 -c 'import finch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/FinchPython/FinchPython120/finch.py", line 10, in <module>
    import finchconnection
  File "/opt/FinchPython/FinchPython120/finchconnection.py", line 33, in <module>
    hid_api = ctypes.CDLL(os.path.join(HIDAPI_LIBRARY_PATH, "libhidapi64.so"))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/FinchPython/libhidapi64.so: cannot open shared object file: No such file or directory

# Fix the HIDAPI_LIB_PATH to match the PYTHONPATH
$ export HIDAPI_LIB_PATH=/opt/FinchPython/FinchPython120

# Expected behavior without a robot connected
$ python3 -c "import finch; finch.Finch()"
Traceback (most recent call last):
  File "/opt/FinchPython/FinchPython120/finchconnection.py", line 77, in open
    self.cmd_id = self.read_cmd_id()
  File "/opt/FinchPython/FinchPython120/finchconnection.py", line 99, in read_cmd_id
    self.send(b'z')
  File "/opt/FinchPython/FinchPython120/finchconnection.py", line 191, in send
    FinchConnection.send(self, command, payload=payload)
  File "/opt/FinchPython/FinchPython120/finchconnection.py", line 111, in send
    raise Exception("Connection to Finch was closed.")
Exception: Connection to Finch was closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/FinchPython/FinchPython120/finch.py", line 16, in __init__
    self.connection.open()
  File "/opt/FinchPython/FinchPython120/finchconnection.py", line 177, in open
    FinchConnection.open(self)
  File "/opt/FinchPython/FinchPython120/finchconnection.py", line 79, in open
    raise Exception("Failed to connect to the Finch robot.")
Exception: Failed to connect to the Finch robot.
```

That last exception is expected if you don't have a Finch robot connected.

We probably need to look into either:
- Putting our extra Finch scripts into `/opt/FinchPython/FinchPython120` and adding that to both path vars
- Moving all the Finch stuff up one directory level

**Comment by kylelaker** [comment]
@ripleymj did we ever decide which of these (or another) options we wanted to go with

**Comment by ripleymj** [comment]
Umm, I think setting the variables to `/opt/FinchPython/FinchPython120` is probably the better option, so it still differentiates the delivered bundle vs the files we add. If it ends up being more effort than that, I wouldn't bother, as it doesn't look like this we'll be used for CS 101 this year.
